version: "3.8"

services:
  app:
    image: ghcr.io/balnarendrasapa/api:latest
    ports:
      - "8000:8000"
      - "8080:8080"

  db:
    image: postgres:latest
    restart: unless-stopped
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: